pub mod analysis;
mod analysis_service;
mod app;
pub mod auth;
pub mod config;
pub mod error;
pub mod fragmenter;
mod health_service;
pub mod http_boundary;
mod ingest_service;
pub mod llm;
mod llm_service;
pub mod meili;
pub mod models;
pub mod mutation;
pub mod parser;
mod rag_service;
mod rag_stream_service;
pub mod repository;
pub mod request_context;
mod request_validation;
pub mod resolver;
mod route_analysis;
mod route_health;
mod route_ingest;
mod route_llm;
mod route_rag;
mod route_registry;
pub mod routes;
pub(crate) mod runtime;
mod shared_audit;
pub mod store;
pub mod tenant_scope;
pub mod tenant_scope_v1;
pub mod upstream;
pub mod util;
pub mod vector_match;

pub use app::AppState;
pub use config::Config;
pub use route_registry::{RouteGuard, RouteMetadata};
pub use routes::{build_router, REGISTERED_ROUTES};
